### Variables
@urlLocal = http://localhost:3000/olx/local/locations
@contentType = application/json

### POST locations bulk
POST {{urlLocal}}/bulk
Content-Type: {{contentType}}

[
    {
        "name": "6824",
        "label": "Pitimbu",
        "value": "6824",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "pitimbu"
        }
    },
    {
        "name": "6825",
        "label": "Cidade da Esperança",
        "value": "6825",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "cidade-da-esperanca"
        }
    },
    {
        "name": "6826",
        "label": "Nossa Senhora da Apresentação",
        "value": "6826",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "nossa-senhora-da-apresentacao"
        }
    },
    {
        "name": "6827",
        "label": "Guarapes",
        "value": "6827",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "guarapes"
        }
    },
    {
        "name": "6828",
        "label": "Praia do Meio",
        "value": "6828",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "praia-do-meio"
        }
    },
    {
        "name": "6829",
        "label": "Pajuçara",
        "value": "6829",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "pajucara"
        }
    },
    {
        "name": "6830",
        "label": "Quintas",
        "value": "6830",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "quintas"
        }
    },
    {
        "name": "6831",
        "label": "Capim Macio",
        "value": "6831",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "capim-macio"
        }
    },
    {
        "name": "6832",
        "label": "Candelária",
        "value": "6832",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "candelaria"
        }
    },
    {
        "name": "6833",
        "label": "Nordeste",
        "value": "6833",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "nordeste"
        }
    },
    {
        "name": "6834",
        "label": "Lagoa Azul",
        "value": "6834",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "lagoa-azul"
        }
    },
    {
        "name": "6835",
        "label": "Nova Descoberta",
        "value": "6835",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "nova-descoberta"
        }
    },
    {
        "name": "6836",
        "label": "Parque das Dunas",
        "value": "6836",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "parque-das-dunas"
        }
    },
    {
        "name": "6837",
        "label": "Dix Sept Rosado",
        "value": "6837",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "dix-sept-rosado"
        }
    },
    {
        "name": "6838",
        "label": "Igapó",
        "value": "6838",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "igapo"
        }
    },
    {
        "name": "6839",
        "label": "Santos Reis",
        "value": "6839",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "santos-reis"
        }
    },
    {
        "name": "6840",
        "label": "Neópolis",
        "value": "6840",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "neopolis"
        }
    },
    {
        "name": "6841",
        "label": "Mãe Luiza",
        "value": "6841",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "mae-luiza"
        }
    },
    {
        "name": "6842",
        "label": "Tirol",
        "value": "6842",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "tirol"
        }
    },
    {
        "name": "6843",
        "label": "Ribeira",
        "value": "6843",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "ribeira"
        }
    },
    {
        "name": "6844",
        "label": "Lagoa Seca",
        "value": "6844",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "lagoa-seca"
        }
    },
    {
        "name": "6845",
        "label": "Petrópolis",
        "value": "6845",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "petropolis"
        }
    },
    {
        "name": "6846",
        "label": "Potengi",
        "value": "6846",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "potengi"
        }
    },
    {
        "name": "6847",
        "label": "Lagoa Nova",
        "value": "6847",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "lagoa-nova"
        }
    },
    {
        "name": "6848",
        "label": "Nossa Senhora De Nazaré",
        "value": "6848",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "nossa-senhora-de-nazare"
        }
    },
    {
        "name": "6849",
        "label": "Areia Preta",
        "value": "6849",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "areia-preta"
        }
    },
    {
        "name": "6850",
        "label": "Barro Vermelho",
        "value": "6850",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "barro-vermelho"
        }
    },
    {
        "name": "6851",
        "label": "Cidade Alta",
        "value": "6851",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "cidade-alta"
        }
    },
    {
        "name": "6852",
        "label": "Planalto",
        "value": "6852",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "planalto"
        }
    },
    {
        "name": "6853",
        "label": "Bom Pastor",
        "value": "6853",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "bom-pastor"
        }
    },
    {
        "name": "6854",
        "label": "Ponta Negra",
        "value": "6854",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "ponta-negra"
        }
    },
    {
        "name": "6855",
        "label": "Cidade Nova",
        "value": "6855",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "cidade-nova"
        }
    },
    {
        "name": "6856",
        "label": "Redinha",
        "value": "6856",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "redinha"
        }
    },
    {
        "name": "6857",
        "label": "Alecrim",
        "value": "6857",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "alecrim"
        }
    },
    {
        "name": "6858",
        "label": "Felipe Camarão",
        "value": "6858",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "felipe-camarao"
        }
    },
    {
        "name": "6859",
        "label": "Salinas",
        "value": "6859",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "salinas"
        }
    },
    {
        "name": "6860",
        "label": "Rocas",
        "value": "6860",
        "parentId": "6823",
        "extraData": {
            "friendlyPath": "rocas"
        }
    }
]

### Get all
GET {{urlLocal}}

### Get by neighborhood
GET {{urlLocal}}?neighborhood=neopolis
